[workspace]
resolver = "3"
members = ["crates/blitz-control-protocol", "crates/tauri-runtime-blitz"]

[workspace.package]
version = "0.1.19"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = true
homepage = "https://github.com/pathscale/tauri-runtime-blitz"
repository = "https://github.com/pathscale/tauri-runtime-blitz"
