[package]
name = "tauri-runtime-blitz"
description = "Tauri runtime backed by Blitz and Boa"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
blitz-script = { path = "../../../blitz-rust/packages/blitz-script", features = ["system-fonts"] }
http = "1"
tauri-runtime = "=2.11.3"
tauri-utils = "=2.9.3"

[features]
macos-private-api = []

[dev-dependencies]
blitz-dom = { path = "../../../blitz-rust/packages/blitz-dom" }
